const LMSAdaptor = require('./LMSAdaptor');
const { exec } = require('child_process');
const path = require('path');
const db = require('../config/db');

class LocalLMSAdaptor extends LMSAdaptor {
    constructor() {
        super();
        this.isConnected = false;
    }

    async connect() {
        console.log("LocalLMSAdaptor: Connecting to local environment...");
        try {
            // Simple check: can we query the DB?
            await db.query('SELECT 1');
            this.isConnected = true;
            console.log("LocalLMSAdaptor: Connected to DB.");
            return true;
        } catch (err) {
            console.error("LocalLMSAdaptor: Connection failed", err);
            this.isConnected = false;
            return false;
        }
    }

    async prepareData() {
        if (!this.isConnected) {
            throw new Error("LMS Not Connected");
        }
        console.log("LocalLMSAdaptor: Triggering ETL process...");
        
        // Path to the python script
        // Assuming standard docker structure: ../PrepaData/etl.py or relative to this service
        // If running locally (node), PrepaData might be a sibling directory.
        const etlScriptPath = path.resolve(__dirname, '../../../PrepaData/etl.py');
        
        return new Promise((resolve, reject) => {
            // We use 'python' command. Ensure python is in PATH.
            exec(`python "${etlScriptPath}"`, (error, stdout, stderr) => {
                if (error) {
                    console.error(`ETL Error: ${error.message}`);
                    return reject(error);
                }
                if (stderr) {
                    console.warn(`ETL Stderr: ${stderr}`);
                }
                console.log(`ETL Output: ${stdout}`);
                resolve(stdout);
            });
        });
    }

    async fetchData() {
         if (!this.isConnected) {
            throw new Error("LMS Not Connected");
        }
        // Example: Fetch the analytics data generated by ETL
        try {
            const result = await db.query('SELECT * FROM student_analytics LIMIT 50');
            return result.rows;
        } catch(err) {
            console.error("Fetch Data Failed:", err);
            throw err;
        }
    }
}

module.exports = LocalLMSAdaptor;
